# Generated by Django 4.2.6 on 2023-11-17 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyFinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(choices=[('Main account', 'Main account'), ('Direct account', 'Direct account'), ('Savings Account', 'Savings Account'), ('Savings Account for a child', 'Savings Account for a child'), ('Saving goals', 'Saving goals'), ('Retirement', 'Retirement')], default='m', max_length=255),
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('destination_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='MyFinance.wallet')),
                ('source_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transactions', to='MyFinance.wallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
