# Generated by Django 4.2.6 on 2023-11-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFinance', '0002_alter_wallet_name_transfers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfers',
            old_name='amount',
            new_name='value',
        ),
    ]
